export const LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_START = 'LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_START';
export const LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_FINISH = 'LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_FINISH';
export const LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_ERROR = 'LOAD_VIDEOS_RECOMMENDATIONS_BY_REGION_ERROR';

export const LOAD_VIDEO_SUGGESTIONS_START = 'LOAD_VIDEO_SUGGESTIONS_START';
export const LOAD_VIDEO_SUGGESTIONS_FINISH = 'LOAD_VIDEO_SUGGESTIONS_FINISH';
export const LOAD_VIDEO_SUGGESTIONS_ERROR = 'LOAD_VIDEO_SUGGESTIONS_ERROR';

export const VIDEOS_SEARCH_START = 'VIDEOS_SEARCH_START';
export const VIDEOS_SEARCH_FINISH = 'VIDEOS_SEARCH_FINISH';
export const VIDEOS_SEARCH_ERROR = 'VIDEOS_SEARCH_ERROR';