export const LOAD_RECOMMENDED_VIDEOS_START = LOAD_RECOMMENDED_VIDEOS_START;
export const LOAD_RECOMMENDED_VIDEOS_FINISH = LOAD_RECOMMENDED_VIDEOS_FINISH;
export const LOAD_RECOMMENDED_VIDEOS_ERROR = LOAD_RECOMMENDED_VIDEOS_ERROR;

export const LOAD_VIDEO_SUGGESTIONS_START = LOAD_VIDEO_SUGGESTIONS_START;
export const LOAD_VIDEO_SUGGESTIONS_FINISH = LOAD_VIDEO_SUGGESTIONS_FINISH;
export const LOAD_VIDEO_SUGGESTIONS_ERROR = LOAD_VIDEO_SUGGESTIONS_ERROR;

export const VIDEOS_SEARCH_START = VIDEOS_SEARCH_START;
export const VIDEOS_SEARCH_FINISH = VIDEOS_SEARCH_FINISH;
export const VIDEOS_SEARCH_ERROR = VIDEOS_SEARCH_ERROR;